### ISSUE TITLE
在Velocity服务端不起作用

### ISSUE THREAD

**Issue by Glucy-2** [EMUnion/AdvancedWhitelistR#3]

**Comment by noionion** [comment]
我万万没想到这玩意居然真的有人用（甚至我还有俩已知bug没修来着）

有空的话我康康吧

**Comment by alex3236** [comment]
请提供详细说明？

**Comment by Glucy-2** [comment]
> 请提供详细说明？

这个插件应该是通过修改whitelist.json实现的
但是Velocity没有这个
所以用不起来

**Comment by alex3236** [comment]
> > 请提供详细说明？
> 
> 这个插件应该是通过修改whitelist.json实现的 但是Velocity没有这个 所以用不起来

既然你知道是修改 whitelist.json 实现的，那么显然这个插件不是为 velocity 设计。
如果你需要 velocity 上的白名单，请使用 velocity 插件，而不是 MCDR 插件。

例如：
https://github.com/plusls/lls-manager
https://github.com/DichuuCraft/bungee-whitelist
https://github.com/mbra/VelocityWhitelist
